### PR TITLE
Init project

### PR DESCRIPTION
**Pull request by luzfcb**

### CODE REVIEW

**Comment by luzfcb** [comment]
Sorry for the bunch of test pull-requests. Github insists on creating a pull-request for the source repository

**Comment by mlissner** [comment]
@luzfcb is this still on your agenda? What happened to our progress?

**Comment by luzfcb** [comment]
@mlissner The base package is almost done in my fork, however, some problems unrelated to this one appeared and they ended up gaining priority on my agenda.
I'll probably work on this next weekend.
Keeping the git history of the extracted files something you would like for the new package?

**Comment by mlissner** [comment]
>  Keeping the git history of the extracted files something you would like for the new package?

That's always nice, but it's not something I'd fret about. I didn't even think that'd be possible, honestly.

**Pull request closed without merging**
